### ISSUE TITLE
Wifiがある店舗情報のリスト表示

### ISSUE THREAD

**Issue by kotaro-miyamoto-99** [miyamoto-taguchi/tokyo-guide-front#14]
**どのような作業をするのか記載して下さい**
GMOのWifi検索アプリのWif一覧リストを参考にWifiのあるカフェの情報を表示するリストを作成します。

[カードに必要な情報]
- 店舗名
- 速度（１〜５を星で）
- 住所

**必要なタスクを箇条書きで記載して下さい**
Atoms：
- [ ] 画像表示
- [ ] 星ボタン

Molecules:
- [ ] レート（星５段階評価）

Org：
- [ ] カフェ情報カード

**Comment by happymgr-s** [comment]
レートはMolになるかもですね！
星一つがatomsに当たって、それを五つ集めたのがMolになる気がします！

**Comment by kotaro-miyamoto-99** [comment]
> レートはMolになるかもですね！ 星一つがatomsに当たって、それを五つ集めたのがMolになる気がします！

了解です！ありがとうございます！
